"""Dodanie relacji usterki na zespoly

Revision ID: a06d591df850
Revises: 
Create Date: 2024-02-02 18:45:47.822003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06d591df850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('czlonkowie_zespolow', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uzytkownicy', ['uzytkownicy_id'], ['id'])

    with op.batch_alter_table('logowanie', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uzytkownicy', ['uzytkownicy_id'], ['id'])

    with op.batch_alter_table('usterki', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uzytkownicy', ['uzytkownicy_id'], ['id'])

    with op.batch_alter_table('usterki_na_zespoly', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'zespoly', ['zespoly_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usterki_na_zespoly', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('usterki', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logowanie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('czlonkowie_zespolow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
