"""Usunięcie historii zdarzeń i typów zdarzenia, dodanie komentarza serwisanta

Revision ID: dd7f20b1ed92
Revises: a06d591df850
Create Date: 2024-02-02 19:14:24.399494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd7f20b1ed92'
down_revision = 'a06d591df850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historia_zdarzen')
    op.drop_table('typ_zdarzenia')
    with op.batch_alter_table('usterki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('komentarz_serwisanta', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usterki', schema=None) as batch_op:
        batch_op.drop_column('komentarz_serwisanta')

    op.create_table('typ_zdarzenia',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('typ_zdarzenia_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nazwa', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='typ_zdarzenia_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('historia_zdarzen',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usterki_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('typ_zdarzenia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tresc_zdarzenia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['typ_zdarzenia_id'], ['typ_zdarzenia.id'], name='historia_zdarzen_typ_zdarzenia_id_fkey'),
    sa.ForeignKeyConstraint(['usterki_id'], ['usterki.id'], name='historia_zdarzen_usterki_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historia_zdarzen_pkey')
    )
    # ### end Alembic commands ###
